config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    member do
      put 'like', to: 'items#upvote'
      put 'dislike', to: 'items#downvote'
    end
  end

  get 'reset', to: 'items#resetvotes'
  get 'item_reset', to: 'items#resetitems'

  get 'unvote_reset', to: 'items#unvotereset'
  get 'vote_reset', to: 'items#votereset'
  root "items#index"

end

app/models/counter.rb
class Counter < ActiveRecord::Base
	belongs_to :user
	acts_as_votable
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :items
	has_many :counter
	acts_as_voter
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    set_counter
    @items = Item.all.order("cached_votes_up DESC")
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to root_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/edit/edit/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to root_path, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    set_item
    @item.liked_by current_user
    redirect_to :back
  end

  def downvote
    set_item
    @item.disliked_by current_user
    redirect_to :back
  end

  def votereset
    set_counter
    @counter.liked_by current_user
    redirect_to root_path
  end

  def unvotereset
    set_counter
    @counter.unliked_by current_user
    redirect_to root_path
  end
    
  def resetvotes
    @users = User.all
    @items = Item.all
    set_counter
    reset_counter
    @users.each do |user|
      @items.each do |item|
        item.unvote_by user
      end
    end
    redirect_to root_path
    flash[:notice]="Votes have been reset"
  end

  def resetitems
    set_counter
    reset_counter
    @items = Item.all
    @items.each do |item|
      item.destroy
    end
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_counter

      if Counter.find_by(id:99999, count:0) #see if the counter exists on db reset
        @counter = Counter.find_by(id:99999) #create an unlikely ID number 
      else
        @counter = Counter.new(id:99999, count:0).save #if the db has reset recently
      end
    end

    def reset_counter
      @counter.destroy
      Counter.new(id:99999, count:0).save 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:item, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= simple_form_for @item do |f| 
  = f.input :item, label: "Name of Item"
  = f.input :body, label: "Description of the item"
  = f.button :submit

app/views/items/_reset.html.haml
- if @counter.voted_on_by? current_user
	I'm having second thoughts...
	%br
	%br
	= link_to "Lets make this work!", unvote_reset_path, class: "btn btn-default"
- else
	These items are no good :(
	%br
	%br
	= link_to "I say we start over!", vote_reset_path, class: "btn btn-default"
%br
.text-muted
	Oh but we make decisions by consensus! 
	%br
	We need at least 50% of user votes. (Currently have
	= @counter.votes_for.size
	of 
	= (User.all.count)/2.round(2)
	votes)

app/views/items/_table.html.haml
%table.table.table-bordered
  %tbody
  - @items.each do |item|
    %tr
      %td= item.item
      / Need user to be logged in to vote
      - if user_signed_in? 
        /Bolding the header of whatever was voted last
        - if (current_user.voted_as_when_voted_for item) == nil
          %td= link_to raw('Like'), like_item_path(item), method: :put
          %td= item.get_upvotes.size
          %td= link_to 'Dislike', dislike_item_path(item), method: :put
          %td= item.get_downvotes.size
        - elsif (current_user.voted_as_when_voted_for item) #if voted in the positive
          %td= link_to raw('<strong><i>Like</i></strong>'), like_item_path(item), method: :put
          %td= item.get_upvotes.size
          %td= link_to 'Dislike', dislike_item_path(item), method: :put
          %td= item.get_downvotes.size
        - else  #if voted in the negative
          %td= link_to 'Like', like_item_path(item), method: :put
          %td= item.get_upvotes.size
          %td= link_to raw('<strong><i>Dislike</i></strong>'), dislike_item_path(item), method: :put
          %td= item.get_downvotes.size
      /Still give them the user details
      %td.text-muted Item submitted: #{item.created_at.strftime("%B %d, %Y")} by #{item.user.email}
        
      - if item.user == current_user
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Delete', item, method: :delete, data: {confirm: 'Are you sure?'}

app/views/items/edit.html.haml
.col-md-6.col-md-offset-3
	%h1 Editing Item

	= render 'form'

	= link_to 'Back', items_path

app/views/items/index.html.haml
.col-md-10.col-md-offset-1

	.page-header

		%h1 Like this (or like that)

	= render 'table' #Holds the votable items
	
	%br
	- if user_signed_in?

		- if @counter.votes_for.size >= (User.all.count)/2.round(3) #Need more than 50% users agreeing to vote
			%br
			%p <strong> THE POWER TO RESET IS YOURS! </strong>
			= link_to "RESET VOTES", reset_path, class: "btn btn-default"
			= link_to "CLEAR ALL ITEMS ON THE LIST", item_reset_path, class: "btn btn-default"

		- else
			%p
				= render 'reset' #Holds the reset votable logic

app/views/items/new.html.haml
.col-md-6.col-md-offset-3

	%h1 New Item

	= render 'form'

	= link_to 'Back', items_path

app/views/items/show.html.haml
%p
  %strong Item:
  = @item.item

  %strongBody:
  = @item.body

app/views/layouts/application.html.haml
!!! 5
%html
%head

	%title Like that
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "Like That", root_path
			.ul.nav.navbar-nav.navbar-right
				- if user_signed_in?
					%li= link_to "New Item", new_item_path
					%li= link_to "Edit Account", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
				- else
					%li= link_to "Sign In", new_user_session_path
					%li= link_to "Sign Up", new_user_registration_path
	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class:"alert alert-info"

		= yield 